services:
  - type: web
    name: explore-nusantara
    env: node
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production